spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
      host: 192.168.43.55
      port: 6379
